package GUI;

import Classes.Classificacao;
import Classes.Jogador;
import EstruturasDeDados.ArrayUnorderedList;
import EstruturasDeDados.UnorderedListADT;
import java.util.Iterator;
import javax.swing.table.DefaultTableModel;

/**
 * Classe para gerir a interface gráfica que apresenta as classificações dos
 * jogadores.
 *
 * @author Grupo 21
 * @author João Pedro Faria Marques nº8180551, T2
 * @author João Pedro Brandão Moreira de Sousa nº8180175, T4
 */
public class MenuClassficacoes extends javax.swing.JFrame {

    /**
     * Lista de classificações.
     */
    private final UnorderedListADT<Classificacao> classificacoes;

    /**
     * Creates new form MenuClassficacoes.
     *
     * @param classifs Lista com todas as classificações a apresentar
     */
    public MenuClassficacoes(UnorderedListADT<Classificacao> classifs) {
        this.classificacoes = (ArrayUnorderedList<Classificacao>) classifs; //AQUI VAI RECEBER OU TODAS AS CLASSFICAÇOES OU UMA LIST SO COM UMA CLASSIFICAÇAO CORRESPONDENTE AQUELE MAPA E DIFICULDADE

        this.setTitle("Classificações");
        this.setDefaultCloseOperation(DISPOSE_ON_CLOSE); //Muda o botão de fechar a janela 'x' para fechar apenas a janela e não o programa
        initComponents();
        this.setResizable(false); //Anula a maximização da janela ou qualquer outro tipo de "resize"

        this.setVisible(true); //Faz aparecer esta janela do jogo
        this.setLocationRelativeTo(null); //Coloca a janela ao centro do 

        jTable1.setModel(new DefaultTableModel());
        DefaultTableModel model = (DefaultTableModel) jTable1.getModel();
        model.addColumn("Posição"); 
        model.addColumn("Jogador");
        model.addColumn("Pontuação");
        model.addColumn("Mapa");
        model.addColumn("Dificuldade");

        /**
         * Para adicionar as classificações à tabela fazemos ao
         * contrário(adicionando sempre a linha nova na posição 0 e o i(posição
         * do jogador) a decrementar em vez de incrementar), tendo em conta que
         * a ordered List ordena de menor para maior ou seja o 0 seria o 1º e
         * assim garantimos que isso não acontece
         */
        Iterator itrClassificacoes = classificacoes.iterator();
        while (itrClassificacoes.hasNext()) {
            Classificacao tempClassificacoes = (Classificacao) itrClassificacoes.next();
            Iterator itrJogadores = tempClassificacoes.getClassificacao().iterator();
            int i = tempClassificacoes.getClassificacao().size() - 1;
            while (itrJogadores.hasNext()) {
                Jogador tempJogador = (Jogador) itrJogadores.next();
                model.insertRow(0, new Object[]{(i + 1), tempJogador.getNome(), tempJogador.getPontos(), tempClassificacoes.getMapa(), tempClassificacoes.getDificuldade()});
                i--;
            }
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jDesktopPane1 = new javax.swing.JDesktopPane();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        jLabelTitulo = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Pos", "Jogador", "Pontuação", "Mapa", "Dificuldade"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.Short.class, java.lang.String.class, java.lang.Integer.class, java.lang.String.class, java.lang.Integer.class
            };
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jTable1.getTableHeader().setReorderingAllowed(false);
        jScrollPane1.setViewportView(jTable1);
        if (jTable1.getColumnModel().getColumnCount() > 0) {
            jTable1.getColumnModel().getColumn(0).setResizable(false);
            jTable1.getColumnModel().getColumn(1).setResizable(false);
            jTable1.getColumnModel().getColumn(2).setResizable(false);
            jTable1.getColumnModel().getColumn(3).setResizable(false);
            jTable1.getColumnModel().getColumn(4).setResizable(false);
        }

        jLabelTitulo.setFont(new java.awt.Font("Lucida Sans Unicode", 0, 24)); // NOI18N
        jLabelTitulo.setForeground(new java.awt.Color(255, 255, 255));
        jLabelTitulo.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabelTitulo.setText("Classificações");

        jDesktopPane1.setLayer(jScrollPane1, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jDesktopPane1.setLayer(jLabelTitulo, javax.swing.JLayeredPane.DEFAULT_LAYER);

        javax.swing.GroupLayout jDesktopPane1Layout = new javax.swing.GroupLayout(jDesktopPane1);
        jDesktopPane1.setLayout(jDesktopPane1Layout);
        jDesktopPane1Layout.setHorizontalGroup(
            jDesktopPane1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jDesktopPane1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jDesktopPane1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 668, Short.MAX_VALUE)
                    .addComponent(jLabelTitulo, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );
        jDesktopPane1Layout.setVerticalGroup(
            jDesktopPane1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jDesktopPane1Layout.createSequentialGroup()
                .addGap(6, 6, 6)
                .addComponent(jLabelTitulo)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 384, Short.MAX_VALUE)
                .addContainerGap())
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jDesktopPane1)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jDesktopPane1)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JDesktopPane jDesktopPane1;
    private javax.swing.JLabel jLabelTitulo;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTable1;
    // End of variables declaration//GEN-END:variables
}
